### ISSUE TITLE
Which is better: GPT or RelGAN for text generation? 

### ISSUE THREAD

**Issue by guotong1988** [weilinie/RelGAN#1]
Based on my understanding, gpt or gpt-2 are using language model loss to train and generate text, which do not contains GAN.

I am so confused about this question. Thank you very much.

**Comment by weilinie** [comment]
GPT or GPT-2 has applied much more network parameters and been trained on much larger dataset than RelGAN, so I think a direct comparison between GPT and RelGAN is somehow unfair. However, both models demonstrated the benefit of self-attention (either with the language modeling loss or the GAN loss) in modeling long-range dependencies.
