### ISSUE TITLE
Where generated text is being stored?

### ISSUE THREAD

**Issue by ghost** [weilinie/RelGAN#11]

**Comment by weilinie** [comment]
They are stored in the  `samples` folder. For example, the full directory could be`experiments/out/20200311/image_coco_rmc_vanilla_RSGAN_adam_bs64_sl20_sn0_dec0_ad-exp_npre150_nadv2000_ms1_hs256_nh2_ds5_dlr1e-4_glr1e-4_tem100_demb64_nrep64_hdim32_sd171/samples`.
