### ISSUE TITLE
How much time it took to run a single cycle of 5 discriminator steps and 1 generator step during the adversarial training?

### ISSUE THREAD

**Issue by abhishek18124** [weilinie/RelGAN#12]

**Comment by weilinie** [comment]
The training itself is pretty fast actually, but the evaluation is time-consuming. If you have slow updates during training, I suggest that you can lower the sample size [here](https://github.com/weilinie/RelGAN/blob/ae8978014db25eb95ee42db30ee84cd709093180/utils/metrics/Bleu.py#L16).

**Comment by abhishek18124** [comment]
Did you try to use RMC in both the generator and discriminator ? I am trying something similar but it is taking very long to train.

**Comment by weilinie** [comment]
I didn’t try that actually. But I guess it shouldn’t take too long as well. Can you disable the evaluation metrics during training and measure the pure training time?
