### ISSUE TITLE
How do i train the model with my own data?

### ISSUE THREAD

**Issue by bharathreddy1997** [weilinie/RelGAN#19]

**Comment by weilinie** [comment]
In general, you can put your own text file (.txt) in the `data` folder, and keep the format to be the same with `image_coco.txt`, where each line means a sentence in your data. For testing, you may need add the test data with the same format in the `data/testdata` folder. The training part should be the same, I think, once you change the naming and directories in the code accordingly.

**Comment by bharathreddy1997** [comment]
Hi, there is no data in adversarial generated samples can you please tell me how to solve it? I am training for a poem dataset. and how to add parser arguments in python console?

**Comment by bharathreddy1997** [comment]
> In general, you can put your own text file (.txt) in the `data` folder, and keep the format to be the same with `image_coco.txt`, where each line means a sentence in your data. For testing, you may need add the test data with the same format in the `data/testdata` folder. The training part should be the same, I think, once you change the naming and directories in the code accordingly.
