### ISSUE TITLE
Reproducing Results

### ISSUE THREAD

**Issue by pclucas14** [weilinie/RelGAN#2]
Hi, 

First of all, thank you for sharing your code! I'm currently performing an empirical evaluation of different GAN approaches, and I would like to include yours. I'm trying to reproduce the results on the `EMNLP2017 WMT News` dataset. 

1) Would it be possible for you to share your pretrained model ?
2) If not, is it sufficient to launch `python real/experiments/emnlp_relgan.py`, wait for training to finish, and extract the weights of the generator ? 

Thanks in advance, 
Lucas

**Comment by weilinie** [comment]
Thanks for your interest in the paper!

1. Currently a pretrained model is not available, but we agree it will be good to provide one so we will release a pretrained model soon. 
2. Yes, you can just launch python` real/experiments/emnlp_relgan.py [job_id] [gpu_id]` and wait for training to finish (it will stop at iter=2200) to get good results. Note that there is a trade-off between quality and diversity so the results at the final step may not be optimal in our trade-off curve.

**Comment by pclucas14** [comment]
great! thanks for your prompt answer

**Comment by oxfordyang2016** [comment]
how to set the job_id ?

**Comment by weilinie** [comment]
The meaning of job_id is decided by lists of arguments from lines 22-31 in emnlp_relgan.py (or coco_relgan.py). So you can set the job_id according to how do you want to choose the arguments from lines 22-31 there.
