### ISSUE TITLE
How long is expected to take to complete the pre-training stage (on single GPU) ?

### ISSUE THREAD

**Issue by tim5go** [weilinie/RelGAN#23]
As titled, it seems it takes forever in the pre-training stage on the EMNLP2017 WMT News dataset.
What is a reasonable time for that?
Is there any configuration / hyper-parameters that I need to be aware of?

**Comment by weilinie** [comment]
I think it’s because the BLEU evaluation has taken much time. So I suggest to use a smaller `sample_size` [here](https://github.com/weilinie/RelGAN/blob/master/utils/metrics/Bleu.py#L16), such as `sample_size`= 50 or 100.

**Comment by tim5go** [comment]
@weilinie 
It doesn't quite help after using a smaller `sample_size=50`.
The estimation completion time is still over **300** hours.

BTW, I am using `tensorflow==1.15`, does it matter?

May I know what hardware specification were you using when you produced the result.

**Comment by weilinie** [comment]
That looks weird. Can you disable the BLEU score evaluation and see if it runs much faster? I didn’t test the code on TF1.15, so I’m not sure right now if it matters. For your reference, I mainly ran experiments on ubuntu 16.04 with GPU GTX 1080ti for ~1.5 days to get the real data results.

**Comment by weilinie** [comment]
Closing it now. Feel free the reopen it if you have further questions.
