### ISSUE TITLE
Using RelGAN for paraphrase generation

### ISSUE THREAD

**Issue by thefirebanks** [weilinie/RelGAN#8]
Hello! Thank you so much for your code. I wanted to try this model on the Quora Question Pair Dataset to see if it could generate reliable paraphrases/sentences. Do you think this is possible? Thanks!

**Comment by weilinie** [comment]
First, let me try to understand: By training a model on the Quora Question Pair, your goal is to generate a rephrasing sentence conditioned on a given sentence. Is that correct? If this is the case, I think it’s worthy to have a try by adding an encoder to take a sentence as its input and modifying the current RelGAN correspondingly to be a conditional GAN.
